CREATE TABLE IF NOT EXISTS `users` (
	`id` CHAR(36) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`gender` ENUM('male', 'female', 'other') NOT NULL DEFAULT 'other',
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`birthdate` DATE NOT NULL,
	`avatar` VARCHAR(255),
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `actions` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`userID` CHAR(36) NOT NULL,
	`token` CHAR(36) NOT NULL UNIQUE,
	`action` ENUM('reset_password', 'create_account', 'activate') NOT NULL,
	`request_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`execution_time` TIMESTAMP NULL,
	`expire_time` TIMESTAMP NOT NULL,
	`is_used` BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `events` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`start_datetime` DATETIME NOT NULL,
	`end_datetime` DATETIME,
	`allDay` BOOLEAN NOT NULL DEFAULT false,
	`userID` CHAR(36) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `notes` (
	`id` CHAR(36) NOT NULL,
	`userID` CHAR(36) NOT NULL,
	`title` VARCHAR(200),
	`content` TEXT NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`last_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `pomodoro` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`userID` CHAR(36) NOT NULL,
	`seconds` INTEGER UNSIGNED NOT NULL,
	`session_date` DATETIME,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `user_videos` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`userID` CHAR(36) NOT NULL,
	`videoID` VARCHAR(20) NOT NULL,
	`title` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `todo_list` (
	`id` CHAR(36) NOT NULL,
	`userID` CHAR(36) NOT NULL,
	`title` VARCHAR(100) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`last_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `todo_item` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`list_id` CHAR(36) NOT NULL,
	`task` VARCHAR(255) NOT NULL,
	`is_done` BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `flashcard_deck` (
	`id` CHAR(36) NOT NULL,
	`userID` CHAR(36) NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `flashcard` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`deckID` CHAR(36) NOT NULL,
	`front_question` TEXT NOT NULL,
	`back_answer` TEXT NOT NULL,
	PRIMARY KEY(`id`)
);

-- CLAVES FORÁNEAS --
ALTER TABLE `user_videos`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `pomodoro`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `actions`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `events`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `notes`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `todo_list`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `todo_item`
ADD FOREIGN KEY(`list_id`) REFERENCES `todo_list`(`id`) ON DELETE CASCADE;

ALTER TABLE `flashcard_deck`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`id`) ON DELETE CASCADE;

ALTER TABLE `flashcard`
ADD FOREIGN KEY(`deckID`) REFERENCES `flashcard_deck`(`id`) ON DELETE CASCADE;